22259-to-24922: changes

diff --git a/SynoBuildConf/build b/SynoBuildConf/build
--- a/SynoBuildConf/build
+++ b/SynoBuildConf/build
@@ -12,7 +12,7 @@ cp -sv /lnxscripts/config/{signing_key,trusted_certificates,untrusted_certificat
 
 export ARCH=${ARCH}
 case "$BUILD_TARGET" in
-	APOLLOLAKE|DENVERTON|KVMX64|REALTEK_RTD1296|BROADWELLNK|MARVELL_ARMADA37XX|PURLEY|COFFEELAKE)
+	APOLLOLAKE|DENVERTON|KVMX64|REALTEK_RTD1296|BROADWELLNK|MARVELL_ARMADA37XX|PURLEY|COFFEELAKE|BROADWELLNTB|NEXTKVMX64|GEMINILAKE)
 		export CROSS_COMPILE=${ToolChainPrefix64} CC=${CC64}
 		KERNEL_CC=${CC64}
 		;;
@@ -22,6 +22,14 @@ case "$BUILD_TARGET" in
 		KERNEL_CC="${CC}"
 		;;
 esac
+
+if [ "$PLATFORM_FAMILY" = "SYNOPLAT_F_X86_64" ] && [ "$BUILD_TARGET" != "DOCKERX64" ]; then
+	ln -s "${SysRootInclude}/hydrogen/hydrogen.h" "${KernelDir}/include/crypto/hydrogen.h"
+	ln -s "${SysRootInclude}/hydrogen/hydrogen.c" "${KernelDir}/crypto/hydrogen/hydrogen.c"
+	ln -s "${SysRootInclude}/hydrogen/impl" "${KernelDir}/crypto/hydrogen/impl"
+	sed -i "s/__RAMDISK_SIGN_PUBLIC_KEY__/$(cat /lnxscripts/config/rd_sign.pub | xxd -i -c 32 )/" \
+		"${KernelDir}/init/initramfs.c"
+fi
 
 case ${MakeClean} in
 	[Yy][Ee][Ss])
@@ -34,15 +42,6 @@ case ${CleanOnly} in
 		return
 		;;
 esac
-
-# Version Infomation
-LNXVERSION="${KernelDir}/.version"
-if [ -f ${VERSION_FILE} ]; then
-	expr $(GetDSMBuildNumber) - 1 > ${LNXVERSION}
-fi
-
-mkdir -p ${ImageDir}/modules
-
 
 case "$BUILD_TARGET" in
 	APOLLOLAKE)
@@ -87,63 +86,173 @@ case "$BUILD_TARGET" in
 		KernelConfig=synoconfigs/coffeelake
 		KernelTarget=bzImage
 		;;
+	BROADWELLNTB)
+		KernelImage=${KernelDir}/arch/x86_64/boot/bzImage
+		KernelConfig=synoconfigs/broadwellntb
+		KernelTarget=bzImage
+		;;
+	NEXTKVMX64)
+		KernelImage=${KernelDir}/arch/x86_64/boot/bzImage
+		KernelConfig=synoconfigs/nextkvmx64
+		KernelTarget=bzImage
+		;;
+	GEMINILAKE)
+		KernelImage=${KernelDir}/arch/x86_64/boot/bzImage
+		KernelConfig=synoconfigs/geminilake
+		KernelTarget=bzImage
+		;;
 	*)
 		SkipThisProject
 		return
 		;;
 esac
 
-# Build kernel and modules
-rm -f ${KernelImage}
-rm -f ${ImageDir}/modules/*
 
-cp -f ${KernelConfig} .config
-mkdir -p include/linux/modules
-make oldconfig
+make_version()
+{
+    if [ -f "$VERSION_FILE" ]; then
+        expr $(GetDSMBuildNumber) - 1 > "$KernelDir/.version"
+    fi
 
-echo "===== Build Synology Linux kernel 4.4.x ====="
-make ${MAKE_FLAGS} ${KernelTarget} modules CC=${KERNEL_CC}
+    [ -f ".debug" ] || return
 
-# Check if kernel is built correctly
-if [ ! -f "${KernelImage}" ]; then
-	echo "Error! ${KernelImage} does not exist!"
-	exit 1;
-fi
+    local _protect_ver="$(dpkg -l | grep -w synoprotection | awk '{print $3}' | cut -d'-' -f2 | head -n1)"
+    local _dsm_ver="$(GetDSMBuildNumber)"
+    if [ -z "$_protect_ver" ]; then
+        WARNING "Unable to detect dpkg 'synoprotection'"
+        return
+    fi
+    if [ "$_dsm_ver" != "$_protect_ver" ]; then
+        WARNING "buildnumber in synoversion/VERSION doesn't match dpkg 'synoprotection'"
+        exit 1
+    fi
+}
 
-if [ ! -z "${MAKE_DTBS}" ]; then
-	echo "===== Build Synology device tree 4.4.x ====="
-	make dtbs DTC_FLAGS="${MAKE_DTC_FLAGS}";
-fi
+config_debug_mode()
+{
+    local _cfg=
+    local _enabled="
+        CONFIG_DEBUG_FS
+        CONFIG_PERF_EVENTS
 
-./scripts/syno_gen_usbmodem_table.sh create-table
-DVB_MODULES_DIR="scripts/DVB/4.4.x"
-if [ -d "$DVB_MODULES_DIR" ]; then
-	rm -rf ${DVB_MODULES_DIR}
-fi
+        CONFIG_DEBUG_INFO
+        CONFIG_FRAME_POINTER
 
-mkdir -p ${DVB_MODULES_DIR}
-find drivers/media -name '*.ko' -exec cp {} ${DVB_MODULES_DIR}/ \;
-cp drivers/base/regmap/regmap-i2c.ko ${DVB_MODULES_DIR};
-cd ./scripts/DVB/
-./generate_dependency_table.py 2>&1
-./generate_VIDPID_table.py 2>&1
-./generate_cleanuped_dependency_table.py 2>&1
-cd -
+        CONFIG_DEBUG_SPINLOCK
+        CONFIG_DEBUG_MUTEXES
+        CONFIG_DEBUG_ATOMIC_SLEEP
 
-# Compare kernel config with re-generated one to see
-# if any changes or new options not reapplied to ${KernelConfig}.
-ConfigDiff=`diff -bu ${KernelConfig} .config`
-if [ -z "$ConfigDiff" ]; then
-	echo
-	echo "Kernel config matches generated .config"
-	echo
-else
-	echo ========== diff -bu ${KernelConfig} .config
-	diff -bu ${KernelConfig} .config
-	echo ========== END of diff
+        CONFIG_FTRACE
+        CONFIG_BRANCH_PROFILE_NONE
+        CONFIG_FUNCTION_TRACER
+        CONFIG_FTRACE_SYSCALLS
+        CONFIG_IRQSOFF_TRACER
+        CONFIG_PREEMPT_TRACER
+        CONFIG_SCHED_TRACER
+        CONFIG_BLK_DEV_IO_TRACE
+        CONFIG_STACK_TRACER
+        CONFIG_UPROBE_EVENT
+        CONFIG_FUNCTION_PROFILER
 
-	echo
-	echo "!!! Diff EXISTS between ${KernelConfig} & generated .config"
-	echo "!!! Recheck before committing."
-	echo
-fi
+        CONFIG_KPROBES
+        CONFIG_BPF_SYSCALL
+    "
+    local _disabled="
+    "
+
+    for _cfg in $_enabled; do
+        INFO "Enable $_cfg"
+        ./scripts/config --enable $_cfg
+    done
+
+    for _cfg in $_disabled; do
+        INFO "Disable $_cfg"
+        ./scripts/config --disable $_cfg
+    done
+}
+
+build_kernel()
+{
+    mkdir -p "$ImageDir/modules"
+    mkdir -p "include/linux/modules"
+    rm -f "$KernelImage"
+    rm -f "$ImageDir/modules/"*
+
+    cp -f "$KernelConfig" .config
+    if [ -f ".debug" ]; then
+        INFO ".debug detected. Configured as debug mode."
+        config_debug_mode
+        make olddefconfig
+    else
+        make oldconfig
+    fi
+
+    INFO "Build Synology Linux kernel 4.4.x"
+    make $MAKE_FLAGS $KernelTarget modules CC=$KERNEL_CC
+
+    # Check if kernel is built correctly
+    if [ ! -f "$KernelImage" ]; then
+        WARNING "Error! $KernelImage does not exist!"
+        exit 1;
+    fi
+}
+
+build_device_tree()
+{
+    if [ ! -z "$MAKE_DTBS" ]; then
+        INFO "Build Synology device tree"
+        make dtbs DTC_FLAGS="$MAKE_DTC_FLAGS";
+    fi
+}
+
+build_usb_modem_table()
+{
+    INFO "Build USB modem table"
+    ./scripts/syno_gen_usbmodem_table.sh create-table
+}
+
+build_dvb_drivers()
+{
+    INFO "Build DVB drivers"
+
+    DVB_MODULES_DIR="scripts/DVB/4.4.x"
+    if [ -d "$DVB_MODULES_DIR" ]; then
+        rm -rf "$DVB_MODULES_DIR"
+    fi
+
+    mkdir -p "$DVB_MODULES_DIR"
+    find drivers/media -name '*.ko' -exec cp {} "$DVB_MODULES_DIR/" \;
+    cp drivers/base/regmap/regmap-i2c.ko "$DVB_MODULES_DIR";
+    cd ./scripts/DVB/
+    ./generate_dependency_table.py 2>&1
+    ./generate_VIDPID_table.py 2>&1
+    ./generate_cleanuped_dependency_table.py 2>&1
+    cd -
+}
+
+check_config()
+{
+    INFO "Compare kernel config with re-generated one"
+
+    ConfigDiff=`diff -bu $KernelConfig .config`
+    if [ -z "$ConfigDiff" ]; then
+        INFO "Kernel config matches generated .config"
+    else
+        WARNING "========== diff -bu $KernelConfig .config"
+        WARNING "$ConfigDiff"
+        WARNING "========== END of diff"
+        WARNING "There's difference between $KernelConfig & .config"
+        WARNING "Please reconfirm your modifications before committing."
+
+        # Build failed if not debug mode
+        [ -f ".debug" ] || WARNING "!!! Diff EXISTS"
+    fi
+}
+
+make_version
+build_kernel
+build_device_tree
+build_usb_modem_table
+build_dvb_drivers
+check_config
+
diff --git a/SynoBuildConf/install-dev b/SynoBuildConf/install-dev
--- a/SynoBuildConf/install-dev
+++ b/SynoBuildConf/install-dev
@@ -4,7 +4,7 @@
 skip=0
 
 case "$BUILD_TARGET" in
-	APOLLOLAKE|DENVERTON|KVMX64|BROADWELLNK|PURLEY|COFFEELAKE)
+	APOLLOLAKE|DENVERTON|KVMX64|BROADWELLNK|PURLEY|COFFEELAKE|BROADWELLNTB|NEXTKVMX64|GEMINILAKE)
 		KERNEL_STRIP=${STRIP64}
 		;;
 	*)
@@ -162,11 +162,13 @@ ModUSB=" \
 	${KernelDir}/drivers/usb/host/xhci-pci.ko \
 	${KernelDir}/drivers/usb/common/usb-common.ko \
 	${KernelDir}/drivers/usb/core/usbcore.ko \
-	${KernelDir}/drivers/usb/host/ehci-hcd.ko \
-	${KernelDir}/drivers/usb/host/ehci-pci.ko \
 	${KernelDir}/drivers/usb/storage/usb-storage.ko \
 	${KernelDir}/drivers/usb/class/cdc-acm.ko \
 	${ModUSBLP} \
+	"
+ModUSBEHCI=" \
+	${KernelDir}/drivers/usb/host/ehci-hcd.ko \
+	${KernelDir}/drivers/usb/host/ehci-pci.ko \
 	"
 ModUSBIP=" \
 	${KernelDir}/drivers/usb/usbip_inf/usbip-host.ko \
@@ -396,6 +398,9 @@ ModXFS=" \
 ModBTRFS=" \
 	${KernelDir}/fs/btrfs/btrfs.ko \
 	"
+ModOVERLAYFS=" \
+	${KernelDir}/fs/overlayfs/overlay.ko \
+	"
 ModCryptoIntel=" \
 	${KernelDir}/arch/x86/crypto/crc32c-intel.ko \
 	${KernelDir}/arch/x86/crypto/aes-x86_64.ko \
@@ -426,6 +431,22 @@ ModDCA=" \
 ModADT=" \
 	${KernelDir}/drivers/hwmon/adt7475.ko \
 	"
+ModNetConsole=" \
+	${KernelDir}/drivers/net/netconsole.ko \
+	"
+
+ModNTB=" \
+	${KernelDir}/drivers/ntb/ntb.ko \
+	${KernelDir}/drivers/ntb/hw/intel/ntb_hw_intel.ko \
+	${KernelDir}/drivers/ntb/ntb_transport.ko \
+	${KernelDir}/drivers/net/ntb_netdev.ko \
+	"
+ModDockerIngress=" \
+	${KernelDir}/net/netfilter/ipvs/ip_vs.ko \
+	${KernelDir}/net/netfilter/ipvs/ip_vs_rr.ko \
+	${KernelDir}/net/netfilter/xt_ipvs.ko \
+	"
+
 ########## Deprecated Module List ##########
 
 ModTalitos=" \
@@ -459,12 +480,16 @@ ModRfkill=" \
 	"
 
 ##################################################
+if [ "$BUILD_TARGET" != BROADWELLNK ]; then
+	ModuleList="${ModuleList} ${ModUSBEHCI}"
+fi
 
 ModuleList="${ModuleList} ${BasicModuleList}"
 
 case "$BUILD_TARGET" in
 	DENVERTON)
 		ModuleList="${ModuleList} ${ModBTRFS}"
+		ModuleList="${ModuleList} ${ModOVERLAYFS}"
 		ModuleList="${ModuleList} ${ModCryptoIntel}"
 		ModuleList="${ModuleList} ${ModI2C}"
 		ModuleList="${ModuleList} ${ModLP3943}"
@@ -485,6 +510,8 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModDVB}"
 		ModuleList="${ModuleList} ${ModDiskPwCtl}"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/net/mdio.ko"
+		ModuleList="${ModuleList} ${ModNetConsole}"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
 
 		;;
 	APOLLOLAKE)
@@ -509,7 +536,8 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModOpenvswitch}"
 		ModuleList="${ModuleList} ${ModDVB}"
 		ModuleList="${ModuleList} ${ModDiskPwCtl}"
-		ModuleList="${ModuleList} ${KernelDir}/lib/zlib_deflate/zlib_deflate.ko"
+		ModuleList="${ModuleList} ${ModNetConsole}"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
 
 		;;
 	KVMX64)
@@ -538,6 +566,7 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModDVB}"
 		ModuleList="${ModuleList} ${ModVirtio}"
 		ModuleList="${ModuleList} ${KernelDir}/lib/zlib_deflate/zlib_deflate.ko"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
 
 		;;
 	REALTEK_RTD1296)
@@ -546,7 +575,6 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModBTRFS}"
 		ModuleList="${ModuleList} ${KernelDir}/crypto/arc4.ko"
 		ModuleList="${ModuleList} ${KernelDir}/crypto/cryptd.ko"
-		ModuleList="${ModuleList} ${KernelDir}/crypto/ocf/cryptodev.ko"
 		ModuleList="${ModuleList} ${KernelDir}/arch/arm64/crypto/aes-neon-blk.ko"
 		ModuleList="${ModuleList} ${KernelDir}/arch/arm64/crypto/aes-ce-blk.ko"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/i2c/algos/i2c-algo-bit.ko"
@@ -570,6 +598,9 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${KernelDir}/crypto/ablk_helper.ko"
 		ModuleList="${ModuleList} ${KernelDir}/crypto/gf128mul.ko"
 		ModuleList="${ModuleList} ${KernelDir}/crypto/lrw.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/mmc/core/mmc_core.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/mmc/card/mmc_block.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/mmc/host/rtk-sdmmc.ko"
 		ModuleList="${ModuleList} ${ModBridge} ${ModTC} ${ModFwSecurity}"
 		ModuleList="${ModuleList} ${ModVlan}"
 		ModuleList="${ModuleList} ${ModUSBserial}"
@@ -583,7 +614,6 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModNFQ}"
 		ModuleList="${ModuleList} ${ModOpenvswitch}"
 		ModuleList="${ModuleList} ${ModDVB}"
-		ModuleList="${ModuleList} ${KernelDir}/drivers/net/ethernet/realtek/r8168/r8168.ko"
 		ModuleList="${ModuleList} ${ModDiskPwCtl}"
 
 		;;
@@ -612,6 +642,37 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModDCA}"
 		ModuleList="${ModuleList} ${ModADT}"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/net/mdio.ko"
+		ModuleList="${ModuleList} ${ModNetConsole}"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
+
+		;;
+	BROADWELLNTB)
+		ModuleList="${ModuleList} ${ModBTRFS}"
+		ModuleList="${ModuleList} ${ModCryptoIntel}"
+		ModuleList="${ModuleList} ${ModI2C}"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/i2c/busses/i2c-i801.ko"
+		ModuleList="${ModuleList} ${ModLP3943}"
+		ModuleList="${ModuleList} ${ModCPUFreq}"
+		ModuleList="${ModuleList} ${ModBridge} ${ModTC} ${ModFwSecurity}"
+		ModuleList="${ModuleList} ${ModVlan}"
+		ModuleList="${ModuleList} ${ModUSBserial}"
+		ModuleList="${ModuleList} ${ModIPsec}"
+		ModuleList="${ModuleList} ${ModUSBModem}"
+		ModuleList="${ModuleList} ${ModEtronUSB}"
+		ModuleList="${ModuleList} ${ModWirless}"
+		ModuleList="${ModuleList} ${ModBluetooth}"
+		ModuleList="${ModuleList} ${ModZram}"
+		ModuleList="${ModuleList} ${ModIPv6Tun}"
+		ModuleList="${ModuleList} ${ModVirtualization}"
+		ModuleList="${ModuleList} ${ModOpenvswitch}"
+		ModuleList="${ModuleList} ${ModNFQ}"
+		ModuleList="${ModuleList} ${ModDVB}"
+		ModuleList="${ModuleList} ${ModDiskPwCtl}"
+		ModuleList="${ModuleList} ${ModDCA}"
+		ModuleList="${ModuleList} ${ModADT}"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/net/mdio.ko"
+		ModuleList="${ModuleList} ${ModNTB}"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
 
 		;;
 	PURLEY)
@@ -640,7 +701,8 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModOpenvswitch}"
 		ModuleList="${ModuleList} ${ModNFQ}"
 		ModuleList="${ModuleList} ${ModDVB}"
-		ModuleList="${ModuleList} ${KernelDir}/lib/zlib_deflate/zlib_deflate.ko"
+		ModuleList="${ModuleList} ${ModNetConsole}"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
 
 		;;
 	MARVELL_ARMADA37XX)
@@ -658,6 +720,7 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/common/usb-common.ko"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/core/usbcore.ko"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/ehci-hcd.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/ehci-orion.ko"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/host/ehci-pci.ko"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/storage/usb-storage.ko"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/usb/class/cdc-acm.ko"
@@ -678,6 +741,7 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModOpenvswitch}"
 		ModuleList="${ModuleList} ${ModDVB}"
 		ModuleList="${ModuleList} ${ModDiskPwCtl}"
+		ModuleList="${ModuleList} ${ModNetConsole}"
 
 		;;
 	COFFEELAKE)
@@ -705,6 +769,63 @@ case "$BUILD_TARGET" in
 		ModuleList="${ModuleList} ${ModDCA}"
 		ModuleList="${ModuleList} ${ModADT}"
 		ModuleList="${ModuleList} ${KernelDir}/drivers/net/mdio.ko"
+		ModuleList="${ModuleList} ${ModNetConsole}"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
+
+		;;
+	NEXTKVMX64)
+		ModuleList="${ModuleList} ${ModBTRFS}"
+		ModuleList="${ModuleList} ${ModCryptoIntel}"
+		ModuleList="${ModuleList} ${ModI2C}"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/i2c/busses/i2c-i801.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/dma/ioat/ioatdma.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/hwmon/adt7475.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/dca/dca.ko"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/net/mdio.ko"
+		ModuleList="${ModuleList} ${ModCPUFreq}"
+		ModuleList="${ModuleList} ${KernelDir}/drivers/cpufreq/cpufreq_conservative.ko"
+		ModuleList="${ModuleList} ${ModBridge} ${ModTC} ${ModFwSecurity}"
+		ModuleList="${ModuleList} ${ModVlan}"
+		ModuleList="${ModuleList} ${ModUSBserial}"
+		ModuleList="${ModuleList} ${ModIPsec}"
+		ModuleList="${ModuleList} ${ModUSBModem}"
+		ModuleList="${ModuleList} ${ModEtronUSB}"
+		ModuleList="${ModuleList} ${ModWirless}"
+		ModuleList="${ModuleList} ${ModBluetooth}"
+		ModuleList="${ModuleList} ${ModZram}"
+		ModuleList="${ModuleList} ${ModIPv6Tun}"
+		ModuleList="${ModuleList} ${ModVirtualization}"
+		ModuleList="${ModuleList} ${ModOpenvswitch}"
+		ModuleList="${ModuleList} ${ModNFQ}"
+		ModuleList="${ModuleList} ${ModDVB}"
+		ModuleList="${ModuleList} ${ModVirtio}"
+		ModuleList="${ModuleList} ${KernelDir}/lib/zlib_deflate/zlib_deflate.ko"
+		ModuleList="${ModuleList} ${ModDockerIngress}"
+
+		;;
+	GEMINILAKE)
+		ModuleList="${ModuleList} ${ModBTRFS}"
+		ModuleList="${ModuleList} ${ModCryptoIntel}"
+		ModuleList="${ModuleList} ${ModI2C}"
+		ModuleList="${ModuleList} ${ModLP3943}"
+		ModuleList="${ModuleList} ${ModCPUFreq}"
+		ModuleList="${ModuleList} ${ModBridge} ${ModTC} ${ModFwSecurity}"
+		ModuleList="${ModuleList} ${ModVlan}"
+		ModuleList="${ModuleList} ${ModUSBserial}"
+		ModuleList="${ModuleList} ${ModIPsec}"
+		ModuleList="${ModuleList} ${ModUSBModem}"
+		ModuleList="${ModuleList} ${ModEtronUSB}"
+		ModuleList="${ModuleList} ${ModWirless}"
+		ModuleList="${ModuleList} ${ModBluetooth}"
+		ModuleList="${ModuleList} ${ModZram}"
+		ModuleList="${ModuleList} ${ModIPv6Tun}"
+		ModuleList="${ModuleList} ${ModVaapi}"
+		ModuleList="${ModuleList} ${ModNFQ}"
+		ModuleList="${ModuleList} ${ModVirtualization}"
+		ModuleList="${ModuleList} ${ModOpenvswitch}"
+		ModuleList="${ModuleList} ${ModDVB}"
+		ModuleList="${ModuleList} ${ModDiskPwCtl}"
+		ModuleList="${ModuleList} ${ModNetConsole}"
 
 		;;
 	*)
@@ -730,19 +851,31 @@ do
 done
 
 case ${BUILD_TARGET} in
-	APOLLOLAKE|DENVERTON|KVMX64|BROADWELLNK|PURLEY|COFFEELAKE)
+	APOLLOLAKE|DENVERTON|KVMX64|BROADWELLNK|PURLEY|COFFEELAKE|BROADWELLNTB|NEXTKVMX64|GEMINILAKE)
 		ZIMAGE="${KernelDir}/arch/x86_64/boot/bzImage"
 		;;
 	REALTEK_RTD1296)
 		lzma -z ${KernelDir}/arch/arm64/boot/Image
 		ZIMAGE="${KernelDir}/arch/arm64/boot/Image.lzma"
 		mkdir -p ${SysRootInclude}/crypto
+
+		# for flash backup model
+		mkimage -A arm64 -C none -T kernel -O linux -a 0b000000 -e 0b000000 -n "$(GetDSMBuildNumber) kernel" -d ${ZIMAGE} ${ZIMAGE}_cksum
+		if [ $? -ne 0 ]; then
+			echo "Failed to do mkimage on ${ZIMAGE}"
+			return 1
+		fi
+		cp -fv ${ZIMAGE}_cksum ${DebDevBuild}/image/zImage_with_cksum
+
 		cp -vf crypto/ocf/cryptodev.h ${SysRootInclude}/crypto
 		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1296-synology-DS418.dtb ${DebDevBuild}/image/dtb_ds418.bin
 		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1293-synology-DS418j.dtb ${DebDevBuild}/image/dtb_ds418j.bin
 		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1296-synology-DS218play.dtb ${DebDevBuild}/image/dtb_ds218play.bin
 		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1296-synology-DS118.dtb ${DebDevBuild}/image/dtb_ds118.bin
 		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1296-synology-DS218.dtb ${DebDevBuild}/image/dtb_ds218.bin
+		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1296-synology-EDS19.dtb ${DebDevBuild}/image/dtb_eds19.bin
+		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1296-synology-RS819.dtb ${DebDevBuild}/image/dtb_rs819.bin
+		cp -vf ${KernelDir}/arch/arm64/boot/dts/realtek/rtd-1293-synology-DS220j.dtb ${DebDevBuild}/image/dtb_ds220j.bin
 		;;
 	MARVELL_ARMADA37XX)
 		lzma -z ${KernelDir}/arch/arm64/boot/Image
